### PR TITLE
Cli serial comms

### PR DESCRIPTION
**Pull request by hcwinsemius**
@ivangayton can you review and merge my code additions of this morning? I basically did quite some work on the serial connection between parent and child, and put together a odm360.py main script that can be called from command line with some input arguments. If additional input arguments are needed then make a new issue plz, but do keep the amount of input arguments limited to only those a user really needs.

Although not committed in this branch (but on earlier branches), I'd appreciate it if you can review the manner in which I pass calls to methods through the serial connection, and the way responses are captured. Most of this functionality is found in camera360serial.py, where methods are programmed that have the exact looks and feels of gphoto2 camera object methods. More low level functionalities to send and receive information (through pickling) is in serial_device.py.

### CODE REVIEW

**Comment by ivangayton** [comment]
I'll take a look at the communication stuff in camera360serial.py and serial_device.py shortly. Certainly makes sense to use an interface that has the same handles as gphoto2.

**Comment by ivangayton** [comment]
Ok, your serial_device.py module looks quite sensible. 

I'm confused as to what you intend to do with the "root" parameter; you don't have anything writing data to storage other than a logger. Are you planning to add functionality to write to files?

**Comment by ivangayton** [comment]
Still looking at the camera360serial.py module. I need to follow the calls around a bit to figure out how it's working; I can't yet see what's getting piped over the serial connection (is the self.photo() object the actual bitmap from the camera sensor?), and I'll have to read things a bit more.

**Comment by smathermather** [comment]
Looks like I have to rename my host:
```
Traceback (most recent call last):
  File "raspi_receive.py", line 18, in <module>
    raise OSError('This function must be deployed on a raspberry pi')
OSError: This function must be deployed on a raspberry pi
```

We should probably be testing this by other means: https://ozzmaker.com/check-raspberry-software-hardware-version-command-line/

**Comment by smathermather** [comment]
Getting an index out of range:
```
python3 ../examples/raspi_connect.py
2020-07-01 10:21:05,681 - odm360 - log - DEBUG - Overwriting log messages in file odm360.log.
2020-07-01 10:21:05,682 - odm360 - raspi_connect - INFO - starting...
Traceback (most recent call last):
  File "../examples/raspi_connect.py", line 18, in <module>
    port, descr = ports[0], descr[0]
IndexError: list index out of range
```

**Comment by hcwinsemius** [comment]
> Still looking at the camera360serial.py module. I need to follow the calls around a bit to figure out how it's working; I can't yet see what's getting piped over the serial connection (is the self.photo() object the actual bitmap from the camera sensor?), and I'll have to read things a bit more.

I suggest that we go over this in a short call.

**Comment by hcwinsemius** [comment]
> Looks like I have to rename my host:
> 
> ```
> Traceback (most recent call last):
>   File "raspi_receive.py", line 18, in <module>
>     raise OSError('This function must be deployed on a raspberry pi')
> OSError: This function must be deployed on a raspberry pi
> ```
> 
> We should probably be testing this by other means: https://ozzmaker.com/check-raspberry-software-hardware-version-command-line/

@smathermather I assumed that a raspberry pi zero would also be called 'raspberrypi' but apparently it is not. I need to hook up a raspi zero to see how to handle this. Can you make an issue for it and assign it to me?

**Pull request merged**
