### PR TITLE
More compact base, experiments in cover, refined pi case

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by smathermather** [comment]
Experiments in case design are still mess, but the base improvements are tested, as are the changes to the pi case portions.

The base was like this, with cameras oriented in a radial pattern. This is actually really good for 360 image creation and terrible for photogrammetry:
image

Also, it happens to be a not-very-compact design, which is a waste of 3D printing materials, and may make the camera harder to balance and carry. So, the redesigned base looks like this:
image

Resulting in an overhead view like this:
image

This also helps with USB cable management.

**Review by ivangayton — COMMENTED** [review]
Appreciate the fact that you still have the comment "This is not inches. No need to fix."

Nice use of modules in the cover! Probably should have done that in the original base, but at the time it didn't seem like the parts would have gotten so sophisticated!

**Comment by smathermather** [comment]
> Appreciate the fact that you still have the comment "This is not inches. No need to fix."

Ha! Oops!

**Comment by smathermather** [comment]
> Nice use of modules in the cover! Probably should have done that in the original base, but at the time it didn't seem like the parts would have gotten so sophisticated!

Thanks! Yeah, things are escalating. :D

**Comment by ivangayton** [comment]
probably should replace the first image in the main Readme with one using the new base design? Or wait for the case?

**Comment by smathermather** [comment]
Nah, we can keep this up to date... standby.

**Comment by ivangayton** [comment]
While we're at it, any reason to keep the blender files?

**Comment by smathermather** [comment]
Ha, nope. Will kill. Standby on the new pull request.

**Comment by smathermather** [comment]
Done.

**Pull request merged**
