### PR TITLE
DB Examples

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by smathermather** [comment]
Ok, we have another table design consideration: This is a start, but it still assumes local storage of all, and we should probably be storing on our child pis and using foreign data wrappers to bring in the data.

**Comment by smathermather** [comment]
A little more on this from my conversation with Ivan regarding how to handle local and remote storage:

The idea is to have each child pi have it's own database with blob storage of the images. So we will need a parent database set-up and a child database setup. The proposed way to combine these is through a foreign data wrapper, or FDW, so that queries, web requests, etc. against the parent database can seamlessly bring back all the data available on the child pis. For example, a user might request a zip file of all the images collected in a project.

To do this we need:
1. A database on each child pi
1. A way to register these child pis on the parent pi
1. FDWs will do the rest in retrieving the data
1. We may need to think through the strategy for dealing with disconnected child pis, etc..

So, @hcwinsemius -- we will need a web endpoint that allows for registering the foreign tables.

**Comment by smathermather** [comment]
Documentation on Postgres FDW: https://www.postgresql.org/docs/current/postgres-fdw.html

First we need to register the extension to expose the functionality:
`CREATE EXTENSION postgres_fdw;`

Now we can register a foreign table:
```CREATE SERVER foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host '192.83.123.89', port '5432', dbname 'foreign_db');
```

We can adapt this example:
```CREATE SERVER foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host '<child_pi_IP>', port '5432', dbname 'child_IP_db'); -- we need to figure out how we are assigning IPs or host names... .
```

**Comment by smathermather** [comment]
Now, we need our local user to be able to access the foreign table as though it is a local user remotely, so we map one to the other:

```
CREATE USER MAPPING FOR local_user
        SERVER foreign_server
        OPTIONS (user 'foreign_user', password 'password');
```

Now to customize for our use:

```
CREATE USER MAPPING FOR odm360
        SERVER child_ip_foreign_server
        OPTIONS (user 'odm360', password 'password');
```

**Comment by smathermather** [comment]
Finally, we actually create what we wanted in the first place: a foreign table from our foreign server to access locally:

```
CREATE FOREIGN TABLE foreign_table (
        id integer NOT NULL,
        data text
)
        SERVER foreign_server
        OPTIONS (schema_name 'some_schema', table_name 'some_table');
```

Which, customized for us might be:

```

-- Yay! Tidy databases
DROP TABLE IF EXISTS photos CASCADE;
CREATE TABLE IF NOT EXISTS photos 
(
	photoid BIGINT GENERATED ALWAYS AS IDENTITY  --renamed: UUID usually is usually a universally unique identifier, and this is a serial
	--,project varchar (50) NOT NULL -- Removing: this only belongs in the project file and will be joined using a foreign key
	,projectid INT
	,survey_run text NOT NULL
	,device text NOT NULL
	,photo_filename text NOT NULL
	,photo BYTEA NOT NULL
	,thumbnail BYTEA
	,PRIMARY KEY(photoid)
	,CONSTRAINT fk_project -- add foreign key constraint referencing the project ID
         FOREIGN KEY(projectid) 
    	   REFERENCES projects(projectid)
	   ON DELETE CASCADE
);

CREATE FOREIGN TABLE foreign_table (
	photoid BIGINT
	,projectid BIGINT
	,survey_run text NOT NULL
	,device text NOT NULL
	,photo_filename text NOT NULL
	,photo BYTEA NOT NULL
	,thumbnail BYTEA
)
        SERVER foreign_server
        OPTIONS (schema_name 'public', table_name 'cameras');
```

**Comment by ivangayton** [comment]
@smathermather I think we actually _do_ want to use UUIDs for photos rather than sequential integers. I can think of many scenarios where individual components of this kind of system are unaware of each other, and collisions are likely. 

I hadn't gotten around to any implementation of that, but I suggest that instead of changing name to reflect the implementation (uuid to photoid) we change the implementation to match the name (and intention)!

**Comment by smathermather** [comment]
Ok. @hcwinsemius -- I updated the samples to reflect Ivan's suggestion on UUIDs. I matched intent with implementation: photo IDs are now UUIDs using the appropriate extension. See top of example SQL for installing the extension, and the updates to everywhere that references photoid (now photouuid).

**Comment by hcwinsemius** [comment]
Ok. I am working on a pythonization of this so tinely to include this.

**Comment by smathermather** [comment]
It's in your parent branch.

**Pull request merged**
